# Introduction

A key function of the IOTC is to gather, analyse and disseminate scientific information, catch and effort statistics, and other data relevant to the conservation and management of the IOTC stocks and the fisheries dependent on them. Following Article XI of the [Agreement](https://iotc.org/sites/default/files/documents/2012/5/25/IOTC%20Agreement.pdf) for the establishment of the IOTC, the CPCs are required to collect and report fisheries data in accordance with the CMMs (see document [IOTC-2024-WPDCS20-05](https://iotc.org/documents/WPDCS/20/05)).

This paper provides an overview of the Data Section's activities for the year 2024, including updates on data-related requests from other Working Parties and progress on recommendations from the previous WPDCS (see [IOTC-2023-WPDCS19-R](https://iotc.org/documents/WPDCS/19/Report)). As part of its activities, the Secretariat provides technical assistance and support to the CPCs to enhance their capacity to report fisheries data in compliance with the CMMs. This encompasses direct requests for assistance from CPCs, as well as the identification of outstanding issues related to data collection, processing, and reporting of fisheries data that need to be addressed, which are incorporated into the programme of work and priorities set by the WPs and the SC