
# Capacity building Activities

As part of the Data Section's tasks, providing support to CPCs is crucial for enhancing the quality of data used for assessment purposes. In 2024, the section conducted seven in-country missions and two technical meetings with CPCs at the Secretariat office. Additionally, the section participated in data-related meetings, mostly virtual, to stay up to date with developments across various domains of the fisheries sector. Details of the main activities, categorized by type and date, are listed in [appendix 1](#DataAv).

## Meeting at the Secretariat

Oman, which the Secretariat has not yet been able to visit, held a two-day meeting at the Secretariat to discuss issues related to their fisheries data. During the discussions, Oman expressed optimism about reviewing both current and past data. However, it was concluded that processing additional datasets, such as catch and effort data and size frequency data, will be challenging without an appropriate system in place. Oman is in the process of hiring a consultant to assess and improve their data management system.

The discussion with the EU (France) at the Secretariat focused on coastal fisheries data. There are gaps in the data that EU (France) can review and update, particularly historical data, and where necessary, disaggregate data for small-scale fisheries.

## Tanzania

### Overview of the mission

Tanzania has received supports with its data collection and reporting systems over the past two consecutive years. The technical mission in 2024 was a follow-up to the mission conducted in 2023. Although Tanzania is one of the CPCs with relatively low catches of IOTC species from coastal fisheries, its industrial fisheries are expanding. Despite the low catches, the reported data are inconsistent in terms of species and fisheries, and not all datasets are being reported.

In 2019, Tanzania launched a pilot project called eCAS, a mobile app for data collectors (enumerators or samplers) to record data at landing sites and upload it directly into a central database. During our most recent visit, the Secretariat learned that eCAS has been upgraded and extended to more landing sites, and developed into a fisheries management platform. The system is well adapted to small-scale fisheries; however, it records limited information for tuna fisheries. Additionally, the system is designed only for coastal fisheries and does not cover industrial fisheries, which should be using logbooks to collect data.

There is often conflicting information between different datasets reported. For example, shark data from Tanzania includes both data collected by samplers and data from the Wildlife Conservation Society (WCS), which is also collaborating with the Tanzanian government on the National Plans of Action (NPOA) for sharks and rays.

During the 2024 mission, the Secretariat learned that Tanzania plans to conduct a frame survey and undertake a comprehensive revision of its data collection system. One of the main objectives of the mission was to train data reporting officers on improving the quality of their submissions, addressing errors from previous reports. The officers were trained on how to extract, compile, and incorporate the required data into the new reporting forms. As the Secretariat is developing new reporting tools, the training focused on the use of these updated tools.


### Outcomes and recommendations

At the end of the mission, the Secretariat, in collaboration with Tanzanian fisheries officers, outlined the following recommendations for the continued improvement of Tanzania's fisheries data:

 - With the increasing availability of shark and ray data from WCS, one of the recommendations is for the government to consolidate WCS data with sample data on sharks and rays, raising the total catch figures before reporting them to the Secretariat.
 
 - Integration of tuna and tuna-like species data reporting requirements into the Fisheries Information Platforms (FiPs).
 
 - Conduct a comprehensive assessment and re-estimation of coastal fisheries catch data for previous years.
 
 - Follow up with industrial fisheries companies to ensure timely submission of required data in accordance with reporting guidelines



## Bangladesh

### Overview of the mission

The technical mission to Bangladesh was conducted following a request from Bangladesh for technical support in implementing IOTC Conservation and Management Measures (CMMs) related to statistical data requirements. As one of the newest IOTC members, the mission involved meetings with various officers across multiple locations engaged in data collection. Additionally, landing sites were visited to better understand the structure of Bangladeshi fisheries. During the mission, Secretariat officers gained knowledge of the data collection and reporting systems in Bangladesh, particularly those managed by the Marine Fisheries Survey Management Unit (MFSMU). MFSMU oversees a variety of fisheries assessment activities, including stock assessments for various species, vessel-based surveys, land-based surveys, data management and reporting, analysis of both fishery-dependent and fishery-independent data, and preparation of materials for various meetings, including IOTC scientific sessions.

However, due to the nature of the fisheries, Bangladesh faces several challenges in its data collection system, which hinder the reporting of accurate data. These challenges include:

 - Insufficient manpower for future data collection efforts
 - Inadequate, inappropriate, or partial data from certain districts (upazilas)
 - Lack of budget and logistical support in upazilas for data collection
 - Misinterpretation of data collection forms


### Outcomes and recommendations

Below are list of outcomes and recommendations from the mission:

  - The Secretariat gained a better understanding of the institutions involved in fisheries monitoring and management, including technical staff and various infrastructures.
  
- The main fisheries targeting tuna and tuna-like species include gillnets, set bag nets, and mid-water trawlers, with several species not currently reported to the Secretariat.

- The Sustainable Coastal and Marine Fisheries Project (SCMFP) has helped improve the data collection system, resulting in large variability in the reported catches in recent years. This suggests that previous data available to the Secretariat and FAO may have been underestimated.

- Assist Bangladesh in adopting the new IOTC reporting forms.

- Bangladesh needs to estimate catches based on the calendar year rather than the fiscal year.

- Follow up on the status of industrial trawlers to determine whether they should be listed under the RAV (Register of Authorized Vessels).

- Promote the use of the Calipseo platform to the Department of Fisheries (DOF) as an appropriate tool for managing data collection and reporting for tuna and tuna-like species.

- Work closely with DOF to build upon the information collected on the species composition of catches for each gear type obtained through the SCMFP project. This includes:  
   (i) revising the current IOTC catch estimates, and  
   (ii) assessing the feasibility of re-estimating the historical time series of catches of tuna and tuna-like species in Bangladesh, in collaboration with DOF.


## Mozambique

### Overview of mission

The mission to Mozambique was conducted following a request for technical assistance to enhance their statistical capabilities and optimize the use of electronic platforms for data submission. This support aims to address the challenges Mozambique faces in fully meeting the data reporting requirements. The last technical data mission in Mozambique was in 2016, which led to some improvements in data reporting. However, in recent years, the quality of the reports from Mozambique has deteriorated, which is concerning, especially as Mozambique is chartering industrial vessels without a clear understanding of the reporting requirements.

The focus of the mission was to review Mozambique’s fisheries data collection and processing systems. Prior to the in-person mission, a preliminary webinar was held with fisheries officers involved in data processing. The meetings revealed several challenges that hinder accurate data reporting.

Mozambique established a taskforce consisting of statistical officers, scientists, and managers from various fisheries departments and institutions to address IOTC reporting requirements, including data submission. Fisheries in Mozambique vary by fishing technique and region, and not all fisheries target tuna and tuna-like species. As a coastal state with vast marine areas, fish consumption is vital for local communities, but tuna species account for only a small percentage of total landings. The limited contribution of tuna fisheries means there is less resources on data collection for tuna and tuna-like species. Like other countries, Mozambique is working toward e-collection of data from landing sites.

Currently, data collection is done by enumerators using paper forms, which are then entered into a database system. With the support of other institutions, Mozambique is trying to adopt a common data collection system used by several countries, [OPEN ARTFISH](https://www.fao.org/fishery/en/knowledgebase/152), to improve the digitalization of artisanal fisheries. However, Open ArTfish has limitations in the types of data it collects and processes, particularly in biological sampling data. To compensate for the lack of biological data, the fisheries department relies on the Oceanographic Institute of Mozambique (InOM).

Although Mozambique uses the reporting forms to submit data, the reports are often incomplete and lack key information. Secretariat officers also conducted training for local officers on how to properly fill in the IOTC forms, particularly focusing on the main data reporting requirements such as retained catches, catch and effort, and size frequency. Since Mozambique also has industrial fisheries (both purse seine and longline), the training also covered data reporting for these fisheries. However, it was challenging to fully complete the forms, as the databases lack some of the essential data for coastal fisheries. Furthermore, the fisheries department is not receiving all required information from the industrial fisheries companies.


### Outcomes and recommendations

The mission was challenging due to a lack of understanding of the reporting requirements and the relatively low emphasis on tuna fisheries in Mozambique. However, the following outcomes and recommendations were outlined:

 - The Secretariat gained a comprehensive understanding of the institutions involved in the management and monitoring of fisheries in Mozambique, covering the main sectors of the fisheries industry and their respective data collection systems.
•  The progress being made to Updates on the ongoing database management platform, with the potential integration of a mobile app for data collection.
•  Follow-up with Mozambique on the use of various data reporting tools and how these tools can enhance their reporting obligations.
•  Encourage Mozambique to participate more actively in IOTC scientific meetings and upcoming regional training on species identification to improve the accuracy of size frequency data reporting.


## Indonesia

### Overview of mission

Indonesia's catches are highly significant in the Indian Ocean, with substantial landings of several IOTC species. However, the complexity of Indonesian fisheries has hindered the collection of accurate fisheries data, resulting in poor quality reporting. In 2024, the Secretariat held several webinars with Indonesia, as well as two in-person missions. The technical support provided to Indonesia focused on re-estimating the catch data for both coastal and industrial fisheries. This is necessary because: (i) all fisheries operate within the National Jurisdiction Area (NJA), (ii) retained catches are estimated broadly for all fisheries, (iii) changes in the catch data of one fishery category affect all other fisheries, and (iv) any modifications to estimation strategies in particular years can lead to inconsistencies in other years. The 2024 missions were prompted by data presented during WPDCS19, which revealed several inconsistencies likely due to gaps in the data collection and/or processing systems over time.

The mission in Indonesia involved reviewing the approach used to address issues identified in the historical catch estimates. It also aimed at developing a methodology for re-estimating catches prior to 2010. During the mission, the Secretariat reviewed the format used for re-estimation, the level of coverage for landing data from logbooks and manual data collection, and the fleet structure used to categorize fisheries. This exercise was hindered by limited historical data collection, scattered repositories, and inconsistencies in data processing.


###  Outcomes and recommendations

 -  Indonesia will provide feedback to the WPDCS19 on the progress made on the re-estimation of the catches.

## Sri Lanka

### Overview of mission

Since 2014, Sri Lanka made significant progress in data collection and reporting systems, improving the quality of the data reporting. However, for several, the Secretariat had provide excel templates for data reporting, which have several limitations, and from old excel version. In line to improve the reporting of data, the Secretariat introduced several reporting tools and new reporting templates recently, trained fisheries officers from CPCs on the utilization of the tools and completion of the templates. However, not all CPCs were able to capture to know-how of completing the new formats with associated tools, especially those with several fishery categories. 
During the IOTC Session in May 2024 (S28), Sri Lanka, clearly indicated that they could not approve the use the new templates in immediately as the staff will need time to better understand the processes. On this call, the Secretariat conduct a support mission in Sri Lanka, to help the fisheries officers to understand the new reporting processes and utilization of the new templates. Besides, focusing on improving data reporting, assessing the status of the Electronic Monitoring (EM) pilot project in Sri Lanka, and reviewing the gillnet fisheries data collection for conducting CPUE analysis, were part of the mission. 

The Secretariat had an overview of the data collection and processing systems of Sri Lanka, which are done by the Department of Fisheries and Aquatic Resources ([DFAR](https://www.fisheriesdept.gov.lk/) and of the National Aquatic Resource Research and Development Agency ([NARA](http://www.nara.ac.lk/)). Review of the historical data of tuna and tuna-like species of Sri Lanka was presented by the Secretariat, with the hope of improving the historical reported data.

The mission focused mainly on training the fisheries officers on the reporting tools, introduction of the online data reporting guidelines. A comparative analysis of the new and old reporting templates was presented showing the feasibility of the new templates and added tools to validate the data. 

The second component, CPUE data requirements, did not work as planned. The Secretariat hired a consultant, Dr. Paul Medley to provide assistance to Sri Lanka in improving the CPUE analysis presented, however, it was not possible to access the data to perform the exercise. 

The third component, EM project, the overview presented by Sri Lanka indicated failure of the project for several reasons: (i) challenges with installation due to vessels construction material; (ii) quick drainage of battery power, and (iii) difficulties in extract the collected data from the initial software use.

Visits to landing sites were crucial to view the various fisheries and type of fishery activities. The landing sites, and the activities of various vessel sizes, clearly denoted the various fisheries categories in Sri Lanka, and the importance of tuna and tuna-like species from each fishery. Samplers and enumerators are very active, whereby the collection of data either as port sampling or logbook are immediately transfer to central databases from the landing ports.
---
Since 2014, Sri Lanka has made significant progress in data collection and reporting systems, resulting in improved data quality. However, for several years, the Secretariat had provided Excel templates for data reporting, which have several limitations and are based on outdated versions. In order to enhance data reporting, the Secretariat recently introduced new reporting tools and updated templates. Fisheries officers from CPCs were trained on how to use these tools and complete the new templates. However, not all CPCs were able to fully grasp the new formats, particularly those with multiple fishery categories.

During the IOTC Session in May 2024 (S28), Sri Lanka clearly indicated that they could not immediately adopt the new templates, as staff would need time to better understand the processes. In response, the Secretariat conducted a support mission in Sri Lanka to assist fisheries officers in understanding the new reporting processes and utilizing the updated templates. Alongside to improving data reporting, the mission included assessing the status of the Electronic Monitoring (EM) pilot project in Sri Lanka and reviewing gillnet fisheries data collection for conducting CPUE analysis.

The Secretariat gained an insight of Sri Lanka’s data collection and processing systems, which are managed by the Department of Fisheries and Aquatic Resources ([DFAR](https://www.fisheriesdept.gov.lk/) and of the National Aquatic Resource Research and Development Agency ([NARA](http://www.nara.ac.lk/)). The Secretariat also reviewed Sri Lanka’s historical data on tuna and tuna-like species with the aim of improving the accuracy of previously reported data.

The mission primarily focused on training fisheries officers on the new reporting tools and introducing online data reporting guidelines. A comparative analysis between the old and new reporting templates was presented, highlighting the benefits of the new templates and the added tools for data validation.

The second component of the mission, related to CPUE data requirements, did not proceed as planned. The Secretariat had hired Dr. Paul Medley, a consultant, to assist Sri Lanka in improving CPUE analysis. However, it was not possible to access the required data to carry out the exercise.

The third component, the EM project, revealed several challenges that led to its failure:

  (i) difficulties with installation due to the vessels' construction materials, 
  (ii) rapid battery drainage, 
  (iii) challenges in extracting collected data from the initial software used.
  
Visits to landing sites were essential for understanding the various fisheries and fishing activities. The landing sites and the activities of different vessel sizes clearly demonstrated the diversity of fisheries categories in Sri Lanka, as well as the importance of tuna and tuna-like species for each fishery. Samplers and enumerators were highly active, ensuring that data collected through port sampling or logbooks was immediately transferred to central databases from the landing ports.


###  Outcomes and recommendations

The reporting tools and templates are new, and therefore faced some few issues, which the Secretariat will need to fix to improve the system. Furthermore, there are some of the fisheries or gear activities that are not encompassed by the new systems, which limited the reporting of some fisheries. The Secretariat is required to review the codes from various tools to ensure all fisheries and characteristics are captured, not only for Sri Lanka, but also from other CPCs.
There remains uncertainty about whether the consultant will obtain access to the data or if Sri Lanka will permit the use of this data for CPUE indices through alternative means. In relation to the use of EM in Sri Lankan fisheries, identifying cost-effective and reliable materials is crucial, and the IOTC should continue to support Sri Lanka in these efforts.

The officers involved in data processing and reporting have demonstrated a better understanding of the tools and templates introduced for reporting. However, there are several areas where the Secretariat must work to improve the system:

- The new reporting tools and templates have encountered some issues that require attention to enhance the system’s functionality.
- Certain fisheries and gear activities are not currently covered by the new systems, limiting the ability to report on some fisheries.
- A review of the codes used in the tools is necessary to ensure that all fisheries and relevant characteristics are accurately captured, not just for Sri Lanka, but for other CPCs as well.

Regarding the CPUE data mining and EM project components of the mission:

- There remains uncertainty as to whether the consultant will gain access to the required data or if Sri Lanka will permit its use for CPUE indices through alternative means.
- In relation to Electronic Monitoring (EM) in Sri Lankan fisheries, identifying cost-effective and reliable materials is crucial. The IOTC should continue to support Sri Lanka in addressing these challenges.


# Workshop

In 2024, the Data Section of the Secretariat conducted two regional data reporting workshops aimed at familiarizing the CPCs with the newly implemented data reporting system.  The workshops were held in two regions:

- **[Eastern Regional Reporting Workshop](https://iotc.org/meetings/iotc-eastern-regional-workshop-enhancing-fisheries-data-reporting)**: Held in Thailand from April 15 to 18, 2024, with 12 participants from eight countries: China, Indonesia, Malaysia, Maldives, Pakistan, Sri Lanka, Philippines, and Thailand.
  - **[Western Regional Reporting Workshop](https://iotc.org/meetings/iotc-western-regional-workshop-enhancing-fisheries-data-reporting)**: Held in Kenya from May 27 to 30, 2024, with 17 participants from 12 countries: Comoros, European Union, Islamic Republic of Iran, Kenya, Madagascar, Mozambique, Oman, Seychelles, Somalia, Tanzania, Bangladesh, and India.

The workshops the different aspects of the data reporting flow:
  - **New Data Reporting Templates**: Excel spreadsheets with separate worksheets for metadata and data reporting.
  - **Reference Code Lists**: A comprehensive list of codes used for reporting fisheries data, accessible on the website, with descriptions of each code.
  - **Fisheries Wizard**: A tool to assist CPCs in defining fishery codes based on the characteristics of each fishery.
  - **Data Reporting Guidelines**: An online document outlining the reporting requirements for each dataset.
  - **Data Validators**: A tool for CPCs to validate data before submission to the Secretariat.
  - **Defining Spatial Areas**: Guidelines to define the spatial areas of fishing for each CPC.

Participants in both workshops were highly engaged and provided valuable recommendations and proposals for improving the new reporting system. The Secretariat also identified some limitations, particularly with the codes describing fisheries and fishing effort.



# Conclusion

The recommendations from the WPDCS19 meeting were thoroughly reviewed by SC26, with most being endorsed or sent for further consideration by S28. While careful attention was given to the new data reporting forms, some CPCs did not approve the transition during S28. However, with additional training provided to individual CPCs, the Secretariat expects that all CPCs will successfully transition to the new system. The intersessional working group established to define the ROS data fields was pivotal, and SC26 endorsed this initiative, with outcomes to be presented at WPDCS20.

Requests made to WPDCS from various working parties primarily focused on the Secretariat collaborating closely with CPCs to review and improve data collection practices.

In 2024, the data section carried out several activities, particularly capacity-building efforts, aimed at improving the quality of data reporting. Notably, many capacity-building missions required follow-up actions to monitor the progress made by the CPCs. CPCs such as Indonesia, with complex fisheries, require continuous support, while for coastal African countries, where tuna fisheries are not as prominent are challenging, as limited efforts and resources are allocated to improving data collection practices.


