# Conclusions

The recommendations from the WPDCS19 meeting were thoroughly reviewed by SC26, with most being endorsed or sent for further consideration by S28. While careful attention was given to the new data reporting forms, some CPCs did not approve the transition during S28. However, with additional training provided to individual CPCs, the Secretariat expects that all CPCs will successfully transition to the new system. The intersessional working group established to define the ROS data fields was pivotal, and SC26 endorsed this initiative, with outcomes to be presented at WPDCS20.

Requests made to WPDCS from various working parties primarily focused on the Secretariat collaborating closely with CPCs to review and improve data collection practices.

In 2024, the data section carried out several activities, particularly capacity-building efforts, aimed at improving the quality of data reporting. Notably, many capacity-building missions required follow-up actions to monitor the progress made by the CPCs. CPCs such as Indonesia, with complex fisheries, require continuous support, while for coastal African countries, where tuna fisheries are not as prominent are challenging, as limited efforts and resources are allocated to improving data collection practices.